udp:
  services:
    emistream:
      loadBalancer:
        servers:
          - address: "{{env "EMIGATE_EMISTREAM_ADDRESS" | default "localhost:10000"}}"

http:
  services:
    auth:
      loadBalancer:
        servers:
          - url: "{{ env "EMIGATE_AUTHGATE_URL" | default "http://localhost:20000" }}"
    emipass:
      loadBalancer:
        servers:
          - url: "{{env "EMIGATE_EMIPASS_URL" | default "http://localhost:11000"}}"
    emistream:
      loadBalancer:
        servers:
          - url: "{{env "EMIGATE_EMISTREAM_URL" | default "http://localhost:10000"}}"
